name: Docker build and push
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 2 * * 0"

env:
  DOCKER_BUILDKIT: 1
  DOCKER_IMAGE: "acornsaustralia/nginx"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
          config: hadolint-ci.yaml

      - name: Build image
        run: docker-compose -f docker-compose.yml build

      - name: Tag images
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          docker tag nginx-unprivileged:latest ${DOCKER_IMAGE}:latest
          docker tag nginx-unprivileged:latest ${DOCKER_IMAGE}:${{ github.run_number }}

      - name: Log into registry
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://index.docker.io/v1/ -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push images
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          docker push ${DOCKER_IMAGE}:latest
          docker push ${DOCKER_IMAGE}:${{ github.run_number }}
