name: Docker build and push
on:   
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 0"

env:
  IMAGE_NAME: nodejs

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
          config: hadolint-ci.yaml

      - name: Build image
        run: docker-compose -f docker-compose.yml build

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://index.docker.io/v1/ -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: docker-compose -f docker-compose.yml push

      - name: Tag this version
        run: docker tag acornsaustralia/nginx:latest acornsaustralia/nginx:${{ github.run_number }}

      - name: Push the versioned image
        run: docker push acornsaustralia/nginx:${{ github.run_number }}
